### ISSUE TITLE
Interpreting de_coef and dv_coef

### ISSUE THREAD

**Issue by salwanbutrus** [yelabucsf/scrna-parameter-estimation#10]
Hello,

Thank you for developing this awesome method! I am curious about the meaning of de_coef and dv_coef. Are they simply fold changes? Along with having the p-values, knowing what these coefficients mean would help me better contextualize the significance of a gene.

Best,
Salwan

**Comment by mincheoly** [comment]
Hi!

In the simplest case of binary comparisons, they are ln(FC) in mean and variability respectively. For more complicated use cases involving replicates and covariates, they are not exactly the fold change between the two groups, but can still be interpreted in the same context.

I do have plans to convert them from ln(FC) to log2(FC) to be more in line other methods, and have clearer labels. 

Thank you for your interest!

Best,
Min Cheol

**Comment by salwanbutrus** [comment]
Great, thank you!
