### ISSUE TITLE
The gene in result_1d is incorrectly displayed.

### ISSUE THREAD

**Issue by Jun-shaw** [yelabucsf/scrna-parameter-estimation#25]
I encountered no errors while executing memento.binary_test_1d, yet the printed results indicate that the genes are represented as numbers. Could this be due to my failure to properly set the row names? I am somewhat unclear regarding the anndata data structure, as this data originates from a transformation of a Seurat object, and I have employed adata.X = csr_matrix(adata.X). I would greatly appreciate any assistance, thank you very much.
![Uploading 1730198946909.png…]()

**Comment by mincheoly** [comment]
Thanks for trying memento! I believe that happens if your index of the `adata.obs` dataframe are numbers. If one of your columns contains the gene names, could you try making sure the index (row names) of the adata.obs contains gene names?

**Comment by Jun-shaw** [comment]
> Thanks for trying memento! I believe that happens if your index of the `adata.obs` dataframe are numbers. If one of your columns contains the gene names, could you try making sure the index (row names) of the adata.obs contains gene names?

Thank you for your response. I meticulously reviewed the results at each step and ultimately discovered that the loss of gene information occurred during the conversion from a Seurat v5 object to a v3 object.

**Comment by mincheoly** [comment]
Good to learn! Thanks for letting me know for the future.
