### ISSUE TITLE
About downloading sample data 'interferon_filtered.h5ad

### ISSUE THREAD

**Issue by ytmed** [yelabucsf/scrna-parameter-estimation#27]
Thank you for publishing such an interesting package.

I want to try the tutorial, but can't find the data ‘/data_volume/memento/demux/interferon_filtered.h5ad’.
Can you tell me how to download the data?

Thank you in advance.

**Comment by mincheoly** [comment]
Thank you for your kind words. 

I'm working on making a more central location for easy access to the tutorial dataset/datasets used in the paper, but in the meantime try: https://memento-examples.s3.us-west-2.amazonaws.com/pbmc-ifnb/interferon_filtered.h5ad

**Comment by ytmed** [comment]
Thank you for your help.
